import { Poppins, Six_Caps } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "500",
  variable: "--font-poppins",
});
const six_caps = Six_Caps({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-clapat",
});

export const metadata = {
  title: "CLAPAT CLONE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
